---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-0
  labels:
    app: kafka
    podindex: "0"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /tmp/data/data-kafka-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-1
  labels:
    app: kafka
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /tmp/data/data-kafka-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-2
  labels:
    app: kafka
    podindex: "2"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /tmp/data/data-kafka-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-zoo-0
  labels:
    app: zookeeper
    podindex: "0"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data/data-zoo-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-zoo-1
  labels:
    app: zookeeper
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data/data-zoo-1
